config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart' 
  get '/cart/:id' => 'cart#add'

  resources :products
  root 'page#home'
  
  
  get 'page/about'

  get 'page/faqs'

  get 'page/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	
	before_action :authenticate_user!, except: [:index]
	
	def add
		id = params[:id]
			#if the cart has already been created, use the existing cart else create a new cart
			if 	session[:cart] then
				cart = session[:cart]
			else
				session[:cart] = {}
				cart = session[:cart]
			end
			#if the product has already been added to the cart, increment the value else set value to 1
			if 	cart[id] then
				cart[id] = cart[id] + 1
			else
				cart[id] = 1
			end
		redirect_to :action => :index
	end  #end add method

	def clearCart
		session[:cart] = nil
		redirect_to :action => :index
	end

	def index
	#if there is a cart, pass it to the page for display else pass an empty value
		if 	session[:cart] then
			@cart = session[:cart]
		else
			@cart = {}
		end


	end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  before_action :authenticate_user!, except: [:home, :add]
  
  def home
  end

  def add
  end  

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category, :subcategory)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1 style ="color: #201bc1; margin-left: 10px"><u>SHOPPING CART</u></h1>  
	<% if @cart.empty? %>
		<h4 style ="color: #201bc1; margin-left: 10px"> .Your Cart Is Empty</H4>
	<% else %>
		<h4 style ="color: #201bc1; margin-left: 10px"><strong><%= link_to'Clear Cart', cart_clear_path %><strong></h4>
	<% end %>

	
<br>

<% total = 0 %>
<div>

	<% @cart.each do |id, quantity| %>
		<% product = Product.find_by_id(id) %>
			<table style="margin-left: 20px">				
				<tr>
					<th colspan="2" style ="color: #ff0000; margin-left: 10px"><strong><%= link_to product.title, product %></strong></th>
				</tr>
				<tr>						
					<td rowspan="3" style="margin-left: 10px"><%= image_tag(product.image_url, width: '120px') %></td>							
					<td style ="color: #201bc1; padding-left: 10px"><strong>Price: <%= number_to_currency(product.price, :unit => '$') %><br>

						Quantity: <%= quantity %></strong><br>
						<% total += quantity * product.price %>						
					</td>
				</tr>
				
				<br>
			</table>
	<% end %>
	<div>			
		<h3 style ="color: #201bc1; margin-left: 10px">
			<strong>Total: <%= number_to_currency(total, :unit => '$') %></strong>
		</h3>
				
	</div>	
			
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Store</title>
    
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
</head>

<body style="background-color:#95c200">

	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "BOOK STORE", root_path, class: "navbar-brand" %>
			</div>		
			<ul class= "nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Sign In", new_user_registration_path %></li>
				<% end %>	
			</ul>
			<ul class="nav navbar-nav navbar-right">		
				<li><%= link_to "Book Shop ", products_path %></li>
				<li><%= link_to "Add Book", new_product_path %></li>	
				<li><%= link_to "Contact Us", page_contact_path %></li>				
			</ul>
		</div>	
	</nav>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>
	
</body>
</html>

app/views/page/contact.html.erb
<h1 style ="color: #201bc1; margin-left: 10px; font-size:35px; color: #fff">CONTACT US - 4GirlBooks.com</h1>  

<table class="contactl" style = "border: 2px solid #fff ; width: 60%; height: 100%; margin-left: 10px">
  
    <tr style="background-color: #f6546a; font:bold 20px">
      <th style = "padding-left: 10px; width: 120px; height: 10px; font-size: 20px; color:#fff"><i>4460 Tucana Court, </i></th>
    </tr>  
    <tr style="background-color: #f6546a; font:bold 20px">  
      <th style = "padding-left: 10px; width: 200px; height: 10px; font-size: 20px; color:#fff"><i>Mississauga, L5R 3K9</i></th>
    </tr>  
	<tr style="background-color: #f6546a; font:bold 20px">  
      <th style = "padding-left: 10px; width: 300px; height: 10px; font-size: 20px; color:#fff"><i>Ontario, Canada.</i></th>      
    </tr>  
    <tr style="background-color: #f6546a; font:bold 20px">  
      <th style = "padding-left: 10px; width: 100px; height: 10px; font-size: 20px; color:#fff"><i>Tel: 416-666-9784</i></th>
    </tr>  
    <tr style="background-color: #f6546a; font:bold 20px">  
      <th style = "padding-left: 10px; width: 100px; height: 10px; font-size: 20px; color:#fff"><i>Email: 4girlbookstore@book.com</i></th>                  
    </tr>
    <tr style="background-color: #f6546a; font:bold 20px">  
    	<td style = "padding-left: 10px"><iframe width="800" height="600" frameborder="1" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.ca/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=4460+Tucana+Court,+Mississauga,+ON&amp;aq=0&amp;oq=4460+Tucana+Court+,+miss&amp;sll=49.303974,-84.738438&amp;sspn=20.0368,53.569336&amp;ie=UTF8&amp;hq=&amp;hnear=4460+Tucana+Crt,+Mississauga,+Ontario+L5B+0E2&amp;t=m&amp;ll=43.596679,-79.642811&amp;spn=0.018648,0.025749&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.ca/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=4460+Tucana+Court,+Mississauga,+ON&amp;aq=0&amp;oq=4460+Tucana+Court+,+miss&amp;sll=49.303974,-84.738438&amp;sspn=20.0368,53.569336&amp;ie=UTF8&amp;hq=&amp;hnear=4460+Tucana+Crt,+Mississauga,+Ontario+L5B+0E2&amp;t=m&amp;ll=43.596679,-79.642811&amp;spn=0.018648,0.025749&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small></td>
    </tr>

  
</table>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
<table style = "border: 3px solid #fff; width: 800px height: 100%; margin-left: 10px">
  
    <tr style="background-color: #f6546a; font:bold 20px; border: 1px solid">
      <th style = "padding-left:10px; width: 150px; height: 50px; font-size: 15px; color:#fff">Image's file name: </th>
      <td class="field" style= "padding-left:10px; width: 300px; height: 50px; font-size: 15px;border: 1px solid"><%= f.text_field :image_url %></td>
    </tr>

    <tr style="background-color: #f6546a; font:bold 20px; border: 1px solid">  
      <th style = "padding-left:10px; width: 150px; height: 50px; font-size: 15px; color:#fff">Title:</th>
      <td class="field" style= "padding-left:10px;  width: 300px; height: 50px; font-size: 15px;border: 1px solid"><strong><%= f.text_field :title %></strong></td>
    </tr>

    <tr style="background-color: #f6546a; font:bold 20px; border: 1px solid">    
      <th style = "padding-left:10px; width: 150px; height: 50px; font-size: 15px; color:#fff">Description:</th>      
      <td class="field" style= "padding-left:10px; width: 300px; height: 100px; font-size: 15px;border: 1px solid"><%= f.text_field :description %></td>        
    </tr>
     
    <tr style="background-color: #f6546a; font:bold 20px; border: 1px solid">     
      <th style = "padding-left:10px; width: 150px; height: 50px; font-size: 15px; color:#fff">Price:</th>
      <td class="field" style= "padding-left:10px;  width: 300px; height: 50px; font-size: 15px;border: 1px solid"><strong><%= f.text_field :price%></strong></td>
    </tr>

    <tr style="background-color: #f6546a; font:bold 20px; border: 1px solid">       
      <th style = "padding-left:10px; width: 150px; height: 50px; font-size: 15px; color:#fff">Category Name:</th>                  
      <td class="field" style= "padding-left:10px;  width: 300px; height: 50px; font-size: 15px;border: 1px solid"><%= f.text_field :category %></td>        
    </tr>
    
    <tr style="background-color: #f6546a; font:bold 20px; border: 1px solid">       
        <td class="actions" colspan="2" style="width: 300px; height:50px; padding-left:130px; font-size: 20px" ><%= f.submit("Create Book") %> </td>
     </tr> 

</table>


<% end %>

app/views/products/edit.html.erb
<h3 style="margin-left: 10px; color:#fff ">Update Book</h3>

<%= render 'form', product: @product %>

<h4 style="margin-left: 10px; color: red ">
	<%= link_to 'Show', @product %>
	<%= link_to 'Back', products_path %>		
</h4>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style ="color: #201bc1; margin-left: 10px">BOOK STORE ~ ~ ~ 4GirlBooks.com</h1>  

<table style = "border: 5px solid ; background-color: white; width: 100%; height: 100%">
  
    <tr style="background-color: #f6546a; font:bold 20px; border: 1px solid">
      <th style = "text-align:center; width: 120px; height: 100px; font-size: 20px; border: 1px solid">IMAGE </th>
      <th style = "text-align:center; width: 200px; height: 100px; font-size: 20px; border: 1px solid">TITLE</th>
      <th style = "text-align:center; width: 300px; height: 100px; font-size: 20px; border: 1px solid">DESCRIPTION</th>      
      <th style = "text-align:center; width: 100px; height: 100px; font-size: 20px; border: 1px solid">PRICE</th>
      <th style = "text-align:center; width: 100px; height: 100px; font-size: 20px; border: 1px solid">CATEGORY</th>            
      <th colspan="4" style = "text-align:center; width: 100px; height: 100px; font-size: 20px; border: 1px solid">SHOPPING</th>
    </tr>
  

  
    <% @products.each do |product| %>
      <tr>
        <td style= "text-align:center; border: 1px solid"><%= image_tag(product.image_url, width: '150px') %></td>
        <td style= "text-align:center; border: 1px solid"><strong><%= product.title %></strong></td>
        <td style= "text-align:left; border: 1px solid"><%= product.description %></td>        
        <td style= "text-align:center; border: 1px solid"><strong><%= product.price %>&nbsp;$</strong></td>
        <td style= "text-align:center; border: 1px solid"><%= product.category %></td>        
        <td style= "text-align:center; width: 65px; height: 100px; border: 1px solid"><%= link_to 'Show', product %></td>
        <td style= "text-align:center; width: 50px; height: 100px;border: 1px solid"><%= link_to 'Edit', edit_product_path(product) %></td>
        <td style= "text-align:center; width: 50px; height: 100px; border: 1px solid"><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure to remove this book ?' } %></td>
        <td style= "text-align:center; width: 100px; height: 100px; border: 1px solid"><a href="/cart/<%= product.id %>"> <strong>Add To Cart</strong></a></td>
      </tr>
    <% end %>
  
</table>

app/views/products/new.html.erb
<h3 style="margin-left: 10px; color: #fff"><strong>New Book</strong></h3>

<%= render 'form', product: @product %>

<h4 style="margin-left: 10px; color: #fff"><strong><%= link_to 'Back', products_path %></strong></h4>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h4 style="margin-left: 20px; color: #fff">
	<strong><%= link_to 'Edit', edit_product_path(@product) %> |
	<%= link_to 'Back', products_path %></strong></h4>


<table style = "border: 5px solid; background-color: white; width: 80%; height: 60%; margin-left: 20px">
    <tr>
        <td colspan="2"><h3><strong><%= @product.title %></strong></h3></td>
    </tr>

    <tr>
        <td rowspan="2"><%= image_tag(@product.image_url, width: '150px') %></td>

        <td style="padding-left: 10px">
        	<strong>Category: </strong><%= @product.category %>
        	<br><strong>Description:</strong><%= @product.description %>
        	<br><strong>Price: <%= number_to_currency(@product.price, :unit => '$') %></strong>
        </td>
    </tr>
    
</table>